version: '3.8'

services:
  oxce:
    image: pedroterzero/oxce
    build:
      context: .
      dockerfile: ./Dockerfile
      target: regular
      args:
        BUILDKIT_INLINE_CACHE: 1
      cache_from:
        - pedroterzero/oxce
    # working_dir: /app

  oxce-rootless:
    image: pedroterzero/oxce:rootless
    build:
      context: .
      dockerfile: ./Dockerfile
      target: rootless
    # working_dir: /app