version: '3.8'

services:
  oxce:
    image: pedroterzero/oxce
    build:
      context: .
      dockerfile: ./Dockerfile
      target: regular
    # working_dir: /app

  oxce-rootless:
    image: pedroterzero/oxce:rootless
    build:
      context: .
      dockerfile: ./Dockerfile
      target: rootless
    # working_dir: /app