on:
 push:
   # branches that are not main
    branches-ignore:
      - main

jobs:
  get_and_build_update:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout code
      uses: actions/checkout@v3
    -
      name: Get the latest version and unpack
      run: bash get-latest.sh
    -
      name: Build the container image
      run: bash build-latest.sh
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Push it to docker hub
      run: |
        docker tag pedroterzero/oxce:latest pedroterzero/oxce:${{ github.ref_name }}
        docker pedroterzero/oxce:${{ github.ref_name }}
