on:
  push
#  schedule:
#    - cron: '0 * * * *'

jobs:
  check_for_update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - run: bash check-for-latest.sh
      id: check_for_update
    - if: ${{ steps.check_for_update.outputs.DO_UPDATE == 1 }}
      run: echo UPDATING!
    # - run: echo "HI I AM UPDATING ${{ steps.check_for_update.outputs.DO_UPDATE }}"
  get_update:
    runs-on: ubuntu-latest
    needs: [check_for_update]
    # if: needs.check_for_update.outputs.DO_UPDATE == 1
    steps:
    - run: echo "HI I AM UPDATING ${{ needs.check_for_update.outputs.DO_UPDATE }}"

# # #      if: ${{ env.DO_UPDATE == '1' }}
# #       # runs-on: ubuntu-latest
# #       # steps:
# #       -
# #       # - if: ${{ env.DO_UPDATE == '1' }}
# #         run: echo "HI I AM UPDATING ${{ steps.check_for_update.outputs.DO_UPDATE }}"
# #       # - name: Checkout code
# #       #   uses: actions/checkout@v2
